services:
  frontend:
    image: node:20-alpine
    container_name: stayly-frontend
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
    stdin_open: true
    command: sh -c "tail -f /dev/null"